train:
  csv_dir: "dataset/10fold_csvs/"
  workers: 4
  weight_path: "artifacts/10fold_weights"
  search_space:
    model.Nx: [200]
    model.rho: [0.9]
    model.input_scale: [0.01]

eval:
  csv_dir: "dataset/10fold_csvs/"
  weight_dir: "artifacts/10fold_weights"
  parallel: true
  workers: 1
